---
- hosts: CentOS
  sudo_user: root
  roles:
  - { role: goozbach.EPEL, epel_enabled: 0 }

- name: Common features for all systems
  hosts: all
  user: root
  roles:
    - common
  tasks:
  - name: Update package
    shell: apt-get update
    when: ansible_os_family == "Debian"

  - name: Install Apache
    apt: name=apache2 state=installed
    when: ansible_os_family == "Debian"

  - name: Install Apache2
    yum: name=httpd state=installed
    when: ansible_os_family == "RedHat"

- name: Install logstash
  hosts: logstash
  user: root
  vars:
     elasticsearch_cluster_name: logstash
     elasticsearch_ip: 127.0.0.1
  roles:
     - { role: elasticsearch, tags: elasticsearch }
     - { role: redis, tags: redis }
     - { role: logstash, tags: logstash,
            with_shipper: True, include_rsyslog: True }
     - { role: kibana, tags: kibana, with_apache: True }
